//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace USAspendingWindow
{
    public partial class Loadtracking
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual System.DateTime loaddate
        {
            get;
            set;
        }
    
        public virtual string loaduser
        {
            get;
            set;
        }
    
        public virtual long recordcount
        {
            get;
            set;
        }

        #endregion
    }
}
