//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace USAspendingWindow
{
    public partial class outofscopefilter
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual System.DateTime insertdate
        {
            get;
            set;
        }
    
        public virtual string insertuser
        {
            get;
            set;
        }
    
        public virtual string filter
        {
            get;
            set;
        }

        public virtual string agency
        {
            get;
            set;
        }
        #endregion
    }
}
