//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace USAspendingWindow
{
    public partial class Current_usaspend
    {
        #region Primitive Properties
    
        public virtual string unique_transaction_id
        {
            get;
            set;
        }
    
        public virtual string transaction_status
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> dollarsobligated
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> baseandexercisedoptionsvalue
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> baseandalloptionsvalue
        {
            get;
            set;
        }
    
        public virtual string maj_agency_cat
        {
            get;
            set;
        }
    
        public virtual string mod_agency
        {
            get;
            set;
        }
    
        public virtual string maj_fund_agency_cat
        {
            get;
            set;
        }
    
        public virtual string contractingofficeagencyid
        {
            get;
            set;
        }
    
        public virtual string contractingofficeid
        {
            get;
            set;
        }
    
        public virtual string fundingrequestingagencyid
        {
            get;
            set;
        }
    
        public virtual string fundingrequestingofficeid
        {
            get;
            set;
        }
    
        public virtual string fundedbyforeignentity
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> signeddate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> effectivedate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> currentcompletiondate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ultimatecompletiondate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> lastdatetoorder
        {
            get;
            set;
        }
    
        public virtual string contractactiontype
        {
            get;
            set;
        }
    
        public virtual string reasonformodification
        {
            get;
            set;
        }
    
        public virtual string typeofcontractpricing
        {
            get;
            set;
        }
    
        public virtual string priceevaluationpercentdifference
        {
            get;
            set;
        }
    
        public virtual string subcontractplan
        {
            get;
            set;
        }
    
        public virtual string lettercontract
        {
            get;
            set;
        }
    
        public virtual string multiyearcontract
        {
            get;
            set;
        }
    
        public virtual string performancebasedservicecontract
        {
            get;
            set;
        }
    
        public virtual string majorprogramcode
        {
            get;
            set;
        }
    
        public virtual string contingencyhumanitarianpeacekeepingoperation
        {
            get;
            set;
        }
    
        public virtual string contractfinancing
        {
            get;
            set;
        }
    
        public virtual string costorpricingdata
        {
            get;
            set;
        }
    
        public virtual string costaccountingstandardsclause
        {
            get;
            set;
        }
    
        public virtual string descriptionofcontractrequirement
        {
            get;
            set;
        }
    
        public virtual string purchasecardaspaymentmethod
        {
            get;
            set;
        }
    
        public virtual string numberofactions
        {
            get;
            set;
        }
    
        public virtual string nationalinterestactioncode
        {
            get;
            set;
        }
    
        public virtual string progsourceagency
        {
            get;
            set;
        }
    
        public virtual string progsourceaccount
        {
            get;
            set;
        }
    
        public virtual string progsourcesubacct
        {
            get;
            set;
        }
    
        public virtual string account_title
        {
            get;
            set;
        }
    
        public virtual string rec_flag
        {
            get;
            set;
        }
    
        public virtual string typeofidc
        {
            get;
            set;
        }
    
        public virtual string multipleorsingleawardidc
        {
            get;
            set;
        }
    
        public virtual string programacronym
        {
            get;
            set;
        }
    
        public virtual string vendorname
        {
            get;
            set;
        }
    
        public virtual string vendoralternatename
        {
            get;
            set;
        }
    
        public virtual string vendorlegalorganizationname
        {
            get;
            set;
        }
    
        public virtual string vendordoingasbusinessname
        {
            get;
            set;
        }
    
        public virtual string divisionname
        {
            get;
            set;
        }
    
        public virtual string divisionnumberorofficecode
        {
            get;
            set;
        }
    
        public virtual string vendorenabled
        {
            get;
            set;
        }
    
        public virtual string vendorlocationdisableflag
        {
            get;
            set;
        }
    
        public virtual string ccrexception
        {
            get;
            set;
        }
    
        public virtual string streetaddress
        {
            get;
            set;
        }
    
        public virtual string streetaddress2
        {
            get;
            set;
        }
    
        public virtual string streetaddress3
        {
            get;
            set;
        }
    
        public virtual string city
        {
            get;
            set;
        }
    
        public virtual string state
        {
            get;
            set;
        }
    
        public virtual string zipcode
        {
            get;
            set;
        }
    
        public virtual string vendorcountrycode
        {
            get;
            set;
        }
    
        public virtual string vendor_state_code
        {
            get;
            set;
        }
    
        public virtual string vendor_cd
        {
            get;
            set;
        }
    
        public virtual string congressionaldistrict
        {
            get;
            set;
        }
    
        public virtual string vendorsitecode
        {
            get;
            set;
        }
    
        public virtual string vendoralternatesitecode
        {
            get;
            set;
        }
    
        public virtual string dunsnumber
        {
            get;
            set;
        }
    
        public virtual string parentdunsnumber
        {
            get;
            set;
        }
    
        public virtual string phoneno
        {
            get;
            set;
        }
    
        public virtual string faxno
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> registrationdate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> renewaldate
        {
            get;
            set;
        }
    
        public virtual string mod_parent
        {
            get;
            set;
        }
    
        public virtual string locationcode
        {
            get;
            set;
        }
    
        public virtual string statecode
        {
            get;
            set;
        }
    
        public virtual string placeofperformancecity
        {
            get;
            set;
        }
    
        public virtual string pop_state_code
        {
            get;
            set;
        }
    
        public virtual string placeofperformancecountrycode
        {
            get;
            set;
        }
    
        public virtual string placeofperformancezipcode
        {
            get;
            set;
        }
    
        public virtual string pop_cd
        {
            get;
            set;
        }
    
        public virtual string placeofperformancecongressionaldistrict
        {
            get;
            set;
        }
    
        public virtual string psc_cat
        {
            get;
            set;
        }
    
        public virtual string productorservicecode
        {
            get;
            set;
        }
    
        public virtual string systemequipmentcode
        {
            get;
            set;
        }
    
        public virtual string claimantprogramcode
        {
            get;
            set;
        }
    
        public virtual string principalnaicscode
        {
            get;
            set;
        }
    
        public virtual string informationtechnologycommercialitemcategory
        {
            get;
            set;
        }
    
        public virtual string gfe_gfp
        {
            get;
            set;
        }
    
        public virtual string useofepadesignatedproducts
        {
            get;
            set;
        }
    
        public virtual string recoveredmaterialclauses
        {
            get;
            set;
        }
    
        public virtual string seatransportation
        {
            get;
            set;
        }
    
        public virtual string contractbundling
        {
            get;
            set;
        }
    
        public virtual string consolidatedcontract
        {
            get;
            set;
        }
    
        public virtual string countryoforigin
        {
            get;
            set;
        }
    
        public virtual string placeofmanufacture
        {
            get;
            set;
        }
    
        public virtual string manufacturingorganizationtype
        {
            get;
            set;
        }
    
        public virtual string agencyid
        {
            get;
            set;
        }
    
        public virtual string piid
        {
            get;
            set;
        }
    
        public virtual string modnumber
        {
            get;
            set;
        }
    
        public virtual string transactionnumber
        {
            get;
            set;
        }
    
        public virtual string fiscal_year
        {
            get;
            set;
        }
    
        public virtual string idvagencyid
        {
            get;
            set;
        }
    
        public virtual string idvpiid
        {
            get;
            set;
        }
    
        public virtual string idvmodificationnumber
        {
            get;
            set;
        }
    
        public virtual string solicitationid
        {
            get;
            set;
        }
    
        public virtual string extentcompeted
        {
            get;
            set;
        }
    
        public virtual string reasonnotcompeted
        {
            get;
            set;
        }
    
        public virtual string numberofoffersreceived
        {
            get;
            set;
        }
    
        public virtual string commercialitemacquisitionprocedures
        {
            get;
            set;
        }
    
        public virtual string commercialitemtestprogram
        {
            get;
            set;
        }
    
        public virtual string smallbusinesscompetitivenessdemonstrationprogram
        {
            get;
            set;
        }
    
        public virtual string a76action
        {
            get;
            set;
        }
    
        public virtual string competitiveprocedures
        {
            get;
            set;
        }
    
        public virtual string solicitationprocedures
        {
            get;
            set;
        }
    
        public virtual string typeofsetaside
        {
            get;
            set;
        }
    
        public virtual string localareasetaside
        {
            get;
            set;
        }
    
        public virtual string evaluatedpreference
        {
            get;
            set;
        }
    
        public virtual string fedbizopps
        {
            get;
            set;
        }
    
        public virtual string research
        {
            get;
            set;
        }
    
        public virtual string statutoryexceptiontofairopportunity
        {
            get;
            set;
        }
    
        public virtual string organizationaltype
        {
            get;
            set;
        }
    
        public virtual Nullable<int> numberofemployees
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> annualrevenue
        {
            get;
            set;
        }
    
        public virtual string firm8aflag
        {
            get;
            set;
        }
    
        public virtual string hubzoneflag
        {
            get;
            set;
        }
    
        public virtual string sdbflag
        {
            get;
            set;
        }
    
        public virtual string issbacertifiedsmalldisadvantagedbusiness
        {
            get;
            set;
        }
    
        public virtual string shelteredworkshopflag
        {
            get;
            set;
        }
    
        public virtual string hbcuflag
        {
            get;
            set;
        }
    
        public virtual string educationalinstitutionflag
        {
            get;
            set;
        }
    
        public virtual string womenownedflag
        {
            get;
            set;
        }
    
        public virtual string veteranownedflag
        {
            get;
            set;
        }
    
        public virtual string srdvobflag
        {
            get;
            set;
        }
    
        public virtual string localgovernmentflag
        {
            get;
            set;
        }
    
        public virtual string minorityinstitutionflag
        {
            get;
            set;
        }
    
        public virtual string aiobflag
        {
            get;
            set;
        }
    
        public virtual string stategovernmentflag
        {
            get;
            set;
        }
    
        public virtual string federalgovernmentflag
        {
            get;
            set;
        }
    
        public virtual string minorityownedbusinessflag
        {
            get;
            set;
        }
    
        public virtual string apaobflag
        {
            get;
            set;
        }
    
        public virtual string tribalgovernmentflag
        {
            get;
            set;
        }
    
        public virtual string baobflag
        {
            get;
            set;
        }
    
        public virtual string naobflag
        {
            get;
            set;
        }
    
        public virtual string saaobflag
        {
            get;
            set;
        }
    
        public virtual string nonprofitorganizationflag
        {
            get;
            set;
        }
    
        public virtual string isothernotforprofitorganization
        {
            get;
            set;
        }
    
        public virtual string isforprofitorganization
        {
            get;
            set;
        }
    
        public virtual string isfoundation
        {
            get;
            set;
        }
    
        public virtual string haobflag
        {
            get;
            set;
        }
    
        public virtual string ishispanicservicinginstitution
        {
            get;
            set;
        }
    
        public virtual string emergingsmallbusinessflag
        {
            get;
            set;
        }
    
        public virtual string hospitalflag
        {
            get;
            set;
        }
    
        public virtual string contractingofficerbusinesssizedetermination
        {
            get;
            set;
        }
    
        public virtual string is1862landgrantcollege
        {
            get;
            set;
        }
    
        public virtual string is1890landgrantcollege
        {
            get;
            set;
        }
    
        public virtual string is1994landgrantcollege
        {
            get;
            set;
        }
    
        public virtual string isveterinarycollege
        {
            get;
            set;
        }
    
        public virtual string isveterinaryhospital
        {
            get;
            set;
        }
    
        public virtual string isprivateuniversityorcollege
        {
            get;
            set;
        }
    
        public virtual string isschoolofforestry
        {
            get;
            set;
        }
    
        public virtual string isstatecontrolledinstitutionofhigherlearning
        {
            get;
            set;
        }
    
        public virtual string isserviceprovider
        {
            get;
            set;
        }
    
        public virtual string receivescontracts
        {
            get;
            set;
        }
    
        public virtual string receivesgrants
        {
            get;
            set;
        }
    
        public virtual string receivescontractsandgrants
        {
            get;
            set;
        }
    
        public virtual string isairportauthority
        {
            get;
            set;
        }
    
        public virtual string iscouncilofgovernments
        {
            get;
            set;
        }
    
        public virtual string ishousingauthoritiespublicortribal
        {
            get;
            set;
        }
    
        public virtual string isinterstateentity
        {
            get;
            set;
        }
    
        public virtual string isplanningcommission
        {
            get;
            set;
        }
    
        public virtual string isportauthority
        {
            get;
            set;
        }
    
        public virtual string istransitauthority
        {
            get;
            set;
        }
    
        public virtual string issubchapterscorporation
        {
            get;
            set;
        }
    
        public virtual string islimitedliabilitycorporation
        {
            get;
            set;
        }
    
        public virtual string isforeignownedandlocated
        {
            get;
            set;
        }
    
        public virtual string isarchitectureandengineering
        {
            get;
            set;
        }
    
        public virtual string isdotcertifieddisadvantagedbusinessenterprise
        {
            get;
            set;
        }
    
        public virtual string iscitylocalgovernment
        {
            get;
            set;
        }
    
        public virtual string iscommunitydevelopedcorporationownedfirm
        {
            get;
            set;
        }
    
        public virtual string iscommunitydevelopmentcorporation
        {
            get;
            set;
        }
    
        public virtual string isconstructionfirm
        {
            get;
            set;
        }
    
        public virtual string ismanufacturerofgoods
        {
            get;
            set;
        }
    
        public virtual string iscorporateentitynottaxexempt
        {
            get;
            set;
        }
    
        public virtual string iscountylocalgovernment
        {
            get;
            set;
        }
    
        public virtual string isdomesticshelter
        {
            get;
            set;
        }
    
        public virtual string isfederalgovernmentagency
        {
            get;
            set;
        }
    
        public virtual string isfederallyfundedresearchanddevelopmentcorp
        {
            get;
            set;
        }
    
        public virtual string isforeigngovernment
        {
            get;
            set;
        }
    
        public virtual string isindiantribe
        {
            get;
            set;
        }
    
        public virtual string isintermunicipallocalgovernment
        {
            get;
            set;
        }
    
        public virtual string isinternationalorganization
        {
            get;
            set;
        }
    
        public virtual string islaborsurplusareafirm
        {
            get;
            set;
        }
    
        public virtual string islocalgovernmentowned
        {
            get;
            set;
        }
    
        public virtual string ismunicipalitylocalgovernment
        {
            get;
            set;
        }
    
        public virtual string isnativehawaiianownedorganizationorfirm
        {
            get;
            set;
        }
    
        public virtual string isotherbusinessororganization
        {
            get;
            set;
        }
    
        public virtual string isotherminorityowned
        {
            get;
            set;
        }
    
        public virtual string ispartnershiporlimitedliabilitypartnership
        {
            get;
            set;
        }
    
        public virtual string isschooldistrictlocalgovernment
        {
            get;
            set;
        }
    
        public virtual string issmallagriculturalcooperative
        {
            get;
            set;
        }
    
        public virtual string issoleproprietorship
        {
            get;
            set;
        }
    
        public virtual string istownshiplocalgovernment
        {
            get;
            set;
        }
    
        public virtual string istriballyownedfirm
        {
            get;
            set;
        }
    
        public virtual string istribalcollege
        {
            get;
            set;
        }
    
        public virtual string isalaskannativeownedcorporationorfirm
        {
            get;
            set;
        }
    
        public virtual string iscorporateentitytaxexempt
        {
            get;
            set;
        }
    
        public virtual string iswomenownedsmallbusiness
        {
            get;
            set;
        }
    
        public virtual string isecondisadvwomenownedsmallbusiness
        {
            get;
            set;
        }
    
        public virtual string isjointventurewomenownedsmallbusiness
        {
            get;
            set;
        }
    
        public virtual string isjointventureecondisadvwomenownedsmallbusiness
        {
            get;
            set;
        }
    
        public virtual string walshhealyact
        {
            get;
            set;
        }
    
        public virtual string servicecontractact
        {
            get;
            set;
        }
    
        public virtual string davisbaconact
        {
            get;
            set;
        }
    
        public virtual string clingercohenact
        {
            get;
            set;
        }
    
        public virtual string otherstatutoryauthority
        {
            get;
            set;
        }
    
        public virtual string prime_awardee_executive1
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> prime_awardee_executive1_compensation
        {
            get;
            set;
        }
    
        public virtual string prime_awardee_executive2
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> prime_awardee_executive2_compensation
        {
            get;
            set;
        }
    
        public virtual string prime_awardee_executive3
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> prime_awardee_executive3_compensation
        {
            get;
            set;
        }
    
        public virtual string prime_awardee_executive4
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> prime_awardee_executive4_compensation
        {
            get;
            set;
        }
    
        public virtual string prime_awardee_executive5
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> prime_awardee_executive5_compensation
        {
            get;
            set;
        }
    
        public virtual string interagencycontractingauthority
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_modified_date
        {
            get;
            set;
        }
    
        public virtual string contract_vehicle
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> expire_date
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> completion_date
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> insert_date
        {
            get;
            set;
        }
    
        public virtual string insert_user
        {
            get;
            set;
        }

        #endregion
    }
}
